name: dart_multer
description: >-
  Utility for converting UploadedFile to dart:io File, with temp disk storage
  and middleware support.
version: 1.0.0
homepage: https://github.com/hassanteslim007/dart_multer
repository: https://github.com/hassanteslim007/dart_multer
issue_tracker: https://github.com/hassanteslim007/dart_multer/issues

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  dart_frog: ^1.2.0
  path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
